### ISSUE TITLE
Not all key codes work in every browser

### ISSUE THREAD

**Issue by epeterson320** [elm-lang/keyboard#3] opened 2016-05-20 17:42 UTC
The arrow keys (key codes 37, 38, 39, 40) do not work in latest Chrome.
Everything except the arrow keys and a few others (Enter, Backspace) register as key code 0 in latest Firefox.

Code to reproduce:

```
import Html exposing (text)
import Html.App as App
import Keyboard

main =
  App.program
    { init = (-1, Cmd.none)
    , update = \code _ -> (code, Cmd.none)
    , subscriptions = always (Keyboard.presses identity)
    , view = toString >> text
    }
```

The latest browser versions at the time of this writing are Firefox 46.0.1 and Chrome 50.0.

**Comment by xarvh** [comment] 2016-06-02 23:57
Confirmed on Chromium: `Keyboard.ups` detects arrows, but `Keyboard.presses` doesn't.

**Comment by jvoigtlaender** [comment] 2016-06-06 10:51
For context, an old pull request against `core`, when `Keyboard.presses` still lived there: https://github.com/elm-lang/core/pull/463.

In particular, the first comment there explains the cause of all this, and what is and what is not possible to achieve in fixing `Keyboard.presses`.

**Comment by jeremy-w** [comment] 2016-08-04 13:57
[MDN notes](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/charCode) that `KeyboardEvent.charCode` is deprecated in favor of `KeyboardEvent.key`, which uses string names for the various flavors of key, including media keys (like "Play" and "Pause") and editing keys (like "Backspace" and "Home").

Here's an example of what that looks like in Firefox 49.0b1:

**Left Arrow**
![captura de pantalla 2016-08-04 a las 09 40 05](https://cloud.githubusercontent.com/assets/29010/17404402/80041df2-5a29-11e6-8063-47309299d4d4.png)

**Key h ("Vim left arrow")**
![captura de pantalla 2016-08-04 a las 09 39 51](https://cloud.githubusercontent.com/assets/29010/17404401/80011940-5a29-11e6-9005-2a85c72e0072.png)

(The keyCode and keyChar bits are logged using `Debug.log` in an [Elm app](https://github.com/jweissman/rogue) that's using 0.17's `elm-lang/keyboard` 1.0.0.)

**Comment by jvoigtlaender** [comment] 2016-08-04 15:04
@jeremy-w, trying to handle media keys and editing keys and whatnot for `keypress` is lost effort, since as explained elsewhere and pointed to above, MDN also says that `keypress` should not fire for those keys at all, and indeed browsers other than Firefox adhere to that specification.

**Comment by jeremy-w** [comment] 2016-08-04 23:24
Keypress is lost effort; it's deprecated: [The KeyboardEvent also had a char attribute that was only used by the keypress event. Since the keypress event has   been deprecated, this attribute was no longer useful and was removed](https://w3c.github.io/uievents/#changes-drafts). The media keys are valid keys though, and they should show up AFAICT for not-deprecated KeyboardEvent events.

**Comment by jvoigtlaender** [comment] 2016-08-05 04:47
> Keypress is lost effort; it's deprecated

If you go far enough back in the context of this issue here, as linked to above, you will already find the suggestion, by me, to remove `Keyboard.presses` from Elm altogether. It wasn't done. It's of course possible to open a new issue proposing (again) to remove `Keyboard.presses`, but the current issue here is about what to do with/for `Keyboard.presses` while it exists.

And then it's simply a fact that it does not make sense to even try to handle non-character keys, because a) it won't work and b) it shouldn't work. (The very same document you linked to clearly says that `keypress` should only fire for character keys.)

> The media keys are valid keys though, and they should show up AFAICT for not-deprecated KeyboardEvent events.

Yes, but again, that's not relevant for the issue at hand here. The issue at hand here is about `Keyboard.presses`. (Nobody complains that arrow keys do not work for `Keyboard.ups` and `Keyboard.downs`. Because they do.)

Again it might make sense to have an issue open about using `key` instead of `keyCode` for Elm's keyboard events. But a) that would have to be a different issue than this one here, for reasons given above, and b) anyway Evan is already aware of that, see the final note in http://package.elm-lang.org/packages/elm-lang/html/1.1.0/Html-Events#keyCode.

**Comment by jvoigtlaender** [comment] 2016-08-05 14:49
I have made a pull request, https://github.com/elm-lang/keyboard/pull/5, that at least makes sure the Elm documentation of this subscription agrees with the W3C specification of the underlying event. (It's impossible for the documentation to agree with the behavior in all browsers, since the browsers behave differently, only some of them true to the specification.)

**Comment by jeremy-w** [comment] 2016-08-05 20:43
That clears it up. We are not forced to hew to what the browser gives us directly, so we could do things like converting key into a keyCode ourselves in order to better support this within Elm, though, no?

## Similarly, we could synthesize press events whenever there's a subscribe and we've observed a down followed by an up event.

Jeremy W. Sherman
https://jeremywsherman.com/ https://jeremywsherman.com/

**Comment by jvoigtlaender** [comment] 2016-08-06 08:29
Yes, in theory one could add extra logic on the Elm side to paper over the misbehavior of some browsers. To isolate Elm users from differences between browsers etc. My old pull request against `core` referenced above tried to do some of that, and in its discussion (the history of it does not begin with that PR, there was an older one that had quite some discussion before Evan asked to start a new one) there were other proposals like actually dropping the non-specification-abiding key presses that Firefox gives for non-character keys. [sarcasm] And look at how successful that PR was. [/sarcasm]

So, in practice, the maximum realistic change I expect can get merged here, with convincing enough justification, is to replace `keyCode` by `which`. Given all I know (the lengthy analysis that went into the mentioned old PR), that would be a strict improvement. `Keyboard.presses` would continue to work in exactly the way it currently does in browsers and situations where it's doing fine, and it would start to work fine in additional browsers and situations. Specifically:
- It would continue to work exactly as it does currently in Chrome.
- It would start to emit events for character keys in Firefox.

**Comment by jvoigtlaender** [comment] 2016-08-06 17:03
@epeterson320, I suggest to close this issue here. It is comprehensively covered by the combination of the following two pull requests:
- #5 (Correct documentation of Keyboard.presses)
- #6 (Use KeyboardEvent.which instead of KeyboardEvent.keyCode)

**Closed as completed** 2017-05-05 02:58 UTC
